# Auto-generated by `make publish-brew` — do not edit manually.
class Edgeparse < Formula
  desc "High-performance PDF-to-Markdown/JSON extraction engine (Rust)"
  homepage "https://github.com/raphaelmansuy/edgeparse"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/raphaelmansuy/edgeparse/releases/download/v0.1.1/edgeparse-0.1.1-aarch64-apple-darwin.tar.gz"
      sha256 "2da6be1c032b2a75361c09874411a8df392d8120457220bf5ee81fe37ff08a4c"
    end
    on_intel do
      url "https://github.com/raphaelmansuy/edgeparse/releases/download/v0.1.1/edgeparse-0.1.1-x86_64-apple-darwin.tar.gz"
      sha256 "e503a07b225f58a4b8d8fa35e78ac5f0d5e845cf18ca760292b274df29c810fb"
    end
  end

  def install
    bin.install "edgeparse"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/edgeparse --version")
  end
end
