# Auto-generated by `make publish-brew` — do not edit manually.
class Edgeparse < Formula
  desc "High-performance PDF-to-Markdown/JSON extraction engine (Rust)"
  homepage "https://github.com/raphaelmansuy/edgeparse"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/raphaelmansuy/edgeparse/releases/download/v0.2.3/edgeparse-0.2.3-aarch64-apple-darwin.tar.gz"
      sha256 "e36627309f563c35adbfb0e3b8d700ed225deb4f15760ce63d225bad5ea38393"
    end
    on_intel do
      url "https://github.com/raphaelmansuy/edgeparse/releases/download/v0.2.3/edgeparse-0.2.3-x86_64-apple-darwin.tar.gz"
      sha256 "ecf374a721a50adf27f47b251f71b5634077cdc069793b1bd292a5700d103f31"
    end
  end

  def install
    bin.install "edgeparse"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/edgeparse --version")
  end
end
