# Auto-generated by `make publish-brew` — do not edit manually.
class Edgeparse < Formula
  desc "High-performance PDF-to-Markdown/JSON extraction engine (Rust)"
  homepage "https://github.com/raphaelmansuy/edgeparse"
  version "0.2.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/raphaelmansuy/edgeparse/releases/download/v0.2.2/edgeparse-0.2.2-aarch64-apple-darwin.tar.gz"
      sha256 "afa6e6a108dce20e1402b9253e59f6346206d8a67f224998cd859edad7d612e1"
    end
    on_intel do
      url "https://github.com/raphaelmansuy/edgeparse/releases/download/v0.2.2/edgeparse-0.2.2-x86_64-apple-darwin.tar.gz"
      sha256 "62a4c04a7c13fa96cbfd1f6201ff06b38dedc0388858b4303cfbf8d15970fb50"
    end
  end

  def install
    bin.install "edgeparse"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/edgeparse --version")
  end
end
